export const USERS_DATA = [
  {
    id: '1',
    name: 'Md Sajadur Rahman',
    email: 'sajadur@example.com',
    password: 'password123',
    role: 'admin',
  },
  {
    id: '2',
    name: 'Ahsan Ahmed',
    email: 'ahsan@example.com',
    password: 'ahsan123',
    role: 'user',
  },
  {
    id: '3',
    name: 'Rahim Uddin',
    email: 'rahim@example.com',
    password: 'rahim123',
    role: 'user',
  },
  {
    id: '4',
    name: 'Karim Hossain',
    email: 'karim@example.com',
    password: 'karim123',
    role: 'user',
  },
  {
    id: '5',
    name: 'Nusrat Jahan',
    email: 'nusrat@example.com',
    password: 'nusrat123',
    role: 'user',
  },
  {
    id: '6',
    name: 'Tamim Iqbal',
    email: 'tamim@example.com',
    password: 'tamim123',
    role: 'user',
  },
  {
    id: '7',
    name: 'Sadia Akter',
    email: 'sadia@example.com',
    password: 'sadia123',
    role: 'user',
  },
  {
    id: '8',
    name: 'Mehedi Hasan',
    email: 'mehedi@example.com',
    password: 'mehedi123',
    role: 'user',
  },
  {
    id: '9',
    name: 'Farhan Khan',
    email: 'farhan@example.com',
    password: 'farhan123',
    role: 'moderator',
  },
  {
    id: '10',
    name: 'Jannatul Ferdous',
    email: 'jannatul@example.com',
    password: 'jannatul123',
    role: 'user',
  },
] as const;
